services:
  littlelemon:
    build: .
    command: python littlelemon/manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - littlelemon_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - littlelemon_net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - littlelemon

networks:
  littlelemon_net:
    external: true
