# Generated by Django 4.2.2 on 2023-06-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="booking", name="no_of_guests", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu", name="inventory", field=models.IntegerField(),
        ),
    ]
